# -*- coding: utf-8 -*-
"""Crop_Management_System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQkp52Ri5aY-8f7EF0UOYqSEUnpc-48x
"""

import pandas as pd
import re
import matplotlib.pyplot as plt
import sys
from getpass import getpass

# ADMIN USERNAME: admin
# ADMIN PASSWORD: password


class User:
    def __init__(self, fname, lname):
      self.firstname = fname
      self.lastname = lname

    def getUsername(self):
      #print(self.firstname, self.lastname)
      print("Enter Username:")
      self.username=input()
    def getPassword(self):
      self.password = getpass("Enter Password:")
      User.password=self.password
      User.username=self.username
      print("****************User Registered******************")

response = int(input("ADMIN(1) |  USER(2)?"))

if(response is 2):
  fname=input("Enter First Name:")
  lname=input("Enter Last Name:")
  x = User(fname, lname)
  x.getUsername()
  x.getPassword()
  response = 3

class Login:
    def __init__(self, username, password):
        self.username = username
        self.password = password
     
        Login.username=self.username
        Login.password=self.password
        Login.token=0
        #Login.AdminAccess=False
        if((User.username == Login.username) and (User.password == Login.password)):
            print("Login Successful!")
            Login.token=1
        else:
            print("Login Failed!")
            Login.token=0
        Login.token=self.token

def bar(f):
    plt.bar(f['Crop_Year'],f['Production'])
                 #set label
    plt.title('Crop Production Details', fontweight = 'bold')
    plt.xticks([1998, 2000, 2002, 2004, 2006, 2008])
    plt.xlabel('Crop Year')
    plt.ylabel('Production')
    plt.show()

def box(f):
    years = []
    for i in range(1997, 2009):
        years.append(f.loc[f.Crop_Year == i]['Production'])
    labels = ['1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008']
    plt.boxplot(years, labels = labels)
    plt.title('Crop Production Details', fontweight = 'bold')
    plt.show()

def line(f):
    plt.figure(figsize = (20,10))
    plt.plot(f['Crop_Year'],f['Production'])
          #set label
    plt.ylabel('Production')
    plt.xlabel('Crop_Year')
    plt.xticks([1998, 2000, 2002, 2004, 2006,2008])
    plt.title('Crop Production Details', fontweight = 'bold')
    plt.show()

if(response == 3):
  uname=input("Enter Username:\n")
  pword = getpass("Enter Password:\n")
  x = Login(uname, pword)
if(response == 1):
  uname=input("Enter Username:\n")
  pword= getpass("Enter Password:\n")
if((uname == "ADMIN" ) and (pword is "password")):
     Login.token=2
     ans=input("DO you want to see the graph (Y/N):")
     if(ans=='Y'):
          print ("The graph of productivity vs crop year")
          types = ['Line', 'Bar', 'Box and Whiskers']
          num = 1,2,3,
          for i, j in zip(num, types):
            print("Press " + str(i) + " for " + j + " graph." )
          no = int(input())
          print("Select the crop")
          print("For Arecanut click 1")
          print("For Other kharif click 2") 
          print("For Rice  click 3")
          print("For Banana click 4")
          print("For Cashewnut click 5")
          print("For Cocunut click 6")
          n=int(input())
          if(n==1):
           #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet2')
          #set plot
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==2):
               #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet3')
                #set plot 
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)  
          elif(n==3):
                #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet4')
                  #set plot
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)   
          elif(n==4):
             #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet5')
                  #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)  
          elif(n==5):
              #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet6')
               #set plot   
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==6):
                    #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet7')
                  #set plot
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
     path1 = "CropsDataFile.xlsx"
     cropdata = pd.read_excel(path1)
     columns_titles = ["Crop_Year","Crop","State_Name","District_Name","Season","Production"]
     cropdata=cropdata.reindex(columns=columns_titles)
     cropdata.to_excel("Newformatdata.xlsx")
     if (Login.token == 2): #and (Login.AdminAccess == True)):
       answer = input("Do you want to insert more details?")
       if (answer == "yes"):
         statename = input("Enter the statename: ")
         districtname = input("Enter the district name: ")
         cropyear = input("Enter the crop year: ")
         season = input("Enter the season: ")
         crop = input("Enter the crop: ")
         area = input("Enter the area: ")
         production = input("Enter the production amount: ")
         new_row = {'State_Name': statename, 'District_Name': districtname, 'Crop_Year': cropyear, 'Season': season, 'Crop': crop, 'Area': area, 'Production': production}
         cropdata = cropdata.append(new_row, ignore_index=True)
         print("This is the new data frame after appending the details that you entered:")
         print(cropdata)
       else:
         print("This is the current data:")
         print(cropdata)
     ans = input("do you want to search for specific details?")
     if ans == 'yes':
            cropdata.reset_index(drop=True)
            year = int(input("Enter the year: "))
            print(cropdata.loc[cropdata['Crop_Year'] == year]['Crop'])
            crop = input("Enter the crop name: ")
            print(cropdata.loc[(cropdata['Crop'] == crop) & (cropdata['Crop_Year'] == year)]['State_Name'])
            state = input("Enter the state name: ")
            print(cropdata.loc[(cropdata['State_Name'] == state) & (cropdata['Crop'] == crop) & (cropdata['Crop_Year'] == year)]['District_Name'])
            district = input("Enter the district name: ")          
            print('This is the data of' + crop + ' according to the entered details.')
            print("\n")
            print(cropdata.loc[(cropdata['District_Name'] == district) & (cropdata['State_Name'] == state) & (cropdata['Crop'] == crop) & (cropdata['Crop_Year'] == year)])
        
     #Login.AdminAccess=True

#class Productivity_Details:
  def TokenCheck(token):
    print(Login.token)
    if(Login.token == 1): # and (Login.AdminAccess == False)):
      ans=input("DO you want to see the graph (Y/N):")
      if(ans=='Y'):
          print ("The graph of productivity vs crop year")
          types = ['Line', 'Bar', 'Box and Whiskers']
          num = 1,2,3
          for i, j in zip(num, types):
            print("Press " + str(i) + " for " + j + " graph." )
          no = int(input())
          print("Select the crop")
          print("For Arecanut click 1")
          print("For Other kharif click 2") 
          print("For Rice  click 3")
          print("For Banana click 4")
          print("For Cashewnut click 5")
          print("For Cocunut click 6")
          n=int(input())
          if(n==1):
           #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet2')
          #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==2):
               #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet3')
                #set plot 
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f) 
          elif(n==3):
                #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet4')
                  #set plot 
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)   
          elif(n==4):
             #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet5')
                  #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==5):
              #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet6')
               #set plot   
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f) 
          elif(n==6):
                    #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet7')
                  #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
      path1 = "CropsDataFile.xlsx"
      cropdata = pd.read_excel(path1)
      columns_titles = ["Crop_Year","Crop","State_Name","District_Name","Season","Production"]
      cropdata=cropdata.reindex(columns=columns_titles)
      cropdata.to_excel("Newformatdata.xlsx")
    #if (Login.token == 2): #and (Login.AdminAccess == True)):

if(response == 3):
  y = TokenCheck(Login.token)
elif(response == 1):
      answer = input("Do you want to insert more details?")
      if (answer == "yes"):
        statename = input("Enter the statename: ")
        districtname = input("Enter the district name: ")
        cropyear = input("Enter the crop year: ")
        season = input("Enter the season: ")
        crop = input("Enter the crop: ")
        area = input("Enter the area: ")
        production = input("Enter the production amount: ")
        new_row = {'State_Name': statename, 'District_Name': districtname, 'Crop_Year': cropyear, 'Season': season, 'Crop': crop, 'Area': area, 'Production': production}
        cropdata = cropdata.append(new_row, ignore_index=True)
        print("This is the new data frame after appending the details that you entered:")
        print(cropdata)
      else:
        ans=input("DO you want to see the graph (Y/N):")
      if(ans=='Y' or 'y'):
          print ("The graph of productivity vs crop year")
          types = ['Line', 'Bar', 'Box and Whiskers']
          num = 1,2,3
          for i, j in zip(num, types):
            print("Press " + str(i) + " for " + j + " graph." )
          no = int(input())
          print("Select the crop")
          print("For Arecanut click 1")
          print("For Other kharif click 2") 
          print("For Rice  click 3")
          print("For Banana click 4")
          print("For Cashewnut click 5")
          print("For Cocunut click 6")
          n=int(input())
          if(n==1):
           #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet2')
          #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==2):
               #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet3')
                #set plot 
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f) 
          elif(n==3):
                #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet4')
                  #set plot 
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)   
          elif(n==4):
             #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet5')
                  #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          elif(n==5):
              #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet6')
               #set plot   
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f) 
          elif(n==6):
                    #set directory
              f=pd.read_excel(r'file1.xlsx','Sheet7')
                  #set plot  
              if no == 1:
                  line(f)
              elif no == 2:
                  bar(f)
              elif no == 3:
                  box(f)
          path1 = "CropsDataFile.xlsx"
          cropdata = pd.read_excel(path1)
          columns_titles = ["Crop_Year","Crop","State_Name","District_Name","Season","Production"]
          cropdata=cropdata.reindex(columns=columns_titles)
          cropdata.to_excel("Newformatdata.xlsx")
      else:
            exit()